force-app/main/default/objects/Book__c/fields/Serial_number__c.field-meta.xml
<CustomField>
    <fullName>Serial_number__c</fullName>
    <label>Serial number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateRecordsWarehouseAndBook.cls
/**
 *@description Manages operaatins of warehouse and book object
 */
public with sharing class CreateRecordsWarehouseAndBook {
  final Integer maxReocrds = 100;
  SerialNumberGenerator serialNumberGenerator;
  
  public CreateRecordsWarehouseAndBook(SerialNumberGenerator serialNumberGenerator ){
    this.serialNumberGenerator = serialNumberGenerator;
  }
  
  public void createRecords() {
    List<sObject> genericList = new List<sObject>();
    
    List<Warehouse__c> warehouses = new List<Warehouse__c>();
    List<Book__c> books = new List<Book__c>();
    
    for (Integer i = 0; i < maxReocrds; i++) {
      Warehouse__c  warehouse = new Warehouse__c(Name='Warehouse__c' + i);
      Book__c book = new Book__c(Name='Book' + i);
      book.Warehouse__r = warehouse;
      books.add(book);
      warehouses.add(warehouse);
    }
    genericList.addAll(warehouses);
    genericList.addAll(books);
    
    insert genericList;
  }
  
  public List<Warehouse__c> getWarehouseAndRelatedBooks(){
    return [SELECT Name, (SELECT Id, Name FROM Books__r)  FROM Warehouse__c];
  }
  
  public List<Book__c> getBooks(){
    return [SELECT Name  FROM Book__c];
  }
  
  public void populateSerialNumber(){
    List<Book__c> books =  getBooks();
    for (Book__c b : books) {
      b.Serial_number__c = serialNumberGenerator.geterate();
    }
    update books;
  }
  
}